In [1]:
import numpy as np

#### 1~10가지 3,3,3 으로 랜덤하게 뽑아라

In [2]:
np.random.randint(1,10,size=(3,3,3))

array([[[8, 1, 2],
        [9, 2, 5],
        [9, 5, 5]],

       [[5, 5, 3],
        [9, 7, 3],
        [3, 4, 6]],

       [[6, 4, 7],
        [2, 4, 6],
        [4, 8, 4]]])

In [3]:
chkboard = np.zeros((8,8), dtype=int)
print (chkboard)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


##### slice : chkboard[행::(슬라이스)2(보폭), ::(슬라이스)2(보폭)]]

In [7]:
chkboard[1::2, ::2] = 1
chkboard[::2, 1::2] = 1
print(chkboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(1,10,5)

array([  1.  ,   3.25,   5.5 ,   7.75,  10.  ])

In [12]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [15]:
a = np.random.randint(1,10, size=(5,5))
a

array([[2, 2, 7, 4, 9],
       [4, 3, 2, 9, 7],
       [2, 3, 7, 9, 6],
       [7, 1, 4, 8, 3],
       [2, 6, 4, 5, 2]])

In [16]:
a[1,4]

7

In [17]:
a[1:3]

array([[4, 3, 2, 9, 7],
       [2, 3, 7, 9, 6]])

### 1.Manipulating

#####  1) reshape(), shape

In [19]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
a.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

###### 원소개수가 몇개인지 모를 때 -1 사용

In [22]:
a.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [23]:
a.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

##### 값을 변환하는 것이 shape

In [24]:
a.shape = (2,3,4)

In [25]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

##### 객체의 속성 구조 변환 transpose(), T

In [26]:
a.transpose()

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [27]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
a.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [29]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

##### 3) ravel() : 일렬로 정렬

In [30]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### Operations

In [33]:
a = np.array([20,30,40,50])
b = np.arange(4)

In [34]:
a

array([20, 30, 40, 50])

In [35]:
b

array([0, 1, 2, 3])

In [36]:
a-b

array([20, 29, 38, 47])

In [37]:
b**2

array([0, 1, 4, 9])

In [38]:
10*a

array([200, 300, 400, 500])

In [39]:
a < 35

array([ True,  True, False, False], dtype=bool)

In [40]:
a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])

In [41]:
a

array([[1, 1],
       [0, 1]])

In [42]:
b

array([[2, 0],
       [3, 4]])

In [43]:
a*b

array([[2, 0],
       [0, 4]])

In [45]:
# 행렬간 곱
np.dot(a,b)

array([[5, 4],
       [3, 4]])

In [47]:
np.matrix([[1,1],[0,1]]) * np.matrix([[2,0],[3,4]])

matrix([[5, 4],
        [3, 4]])

###### Universion functions

In [48]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.sqrt(a)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [50]:
np.exp(a)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

### Data Analysis Example with Numpy

In [51]:
from numpy import genfromtxt
import datetime
import matplotlib.pyplot as plt
%matplotlib inline

In [52]:
data = np.genfromtxt('./data/2015_weather.csv', delimiter=',', dtype='object', names=True) # names : header값

OSError: ./data/2015_weather.csv not found.

In [53]:
data

NameError: name 'data' is not defined

In [ ]:
data['PLANT_ID']; data[0]

In [ ]:
data['WTHR_MAX']

In [ ]:
max_lst = np.where(data['LATITUDE'] == b'37.5457649', data['WTHR_MAX'], False)
max_lst

In [ ]:
WTHR_MAX = []

In [ ]:
for i in range(len(max_lst)):
    if max_lst[i] != False:
        WTHR_MAX.append(max_lst[i])

In [ ]:
plt.plot(WTHR_MAX)