In [1]:
import tensorflow as tf

In [2]:
# placeholder : 주로 학습을 하기 위한 데이터 사용을 위한 그릇
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [3]:
x_data = [[1,2,3], [4,5,6]]

In [4]:
# Variable : 그래프 계산 시 사용될 최적화 변수. 신경망의 weight나 bias 설정할 때 사용
# tf.random_normal : 각 변수들의 초기값을 정규분포 랜덤 값을 초기화
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

In [5]:
# 변수들을 계산할 수식
expr = tf.matmul(X,W)+b

In [6]:
sess = tf.Session()
# Variable의 값들을 초기화 하기 위해 다음 내용 실행
sess.run(tf.global_variables_initializer())

In [7]:
print("===x_data===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
# expr 수식에는 X라는 값이 필요
# expr 실행 시 이 변수에 대한 실제 입력값을 feed_dict 형태로 넣어줘야함.
print(sess.run(expr, feed_dict={X: x_data}))

===x_data===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[ 0.40425119  1.31204152]
 [ 0.5830915   0.43483976]
 [-0.10993625 -0.48211002]]
=== b ===
[[-1.04238117]
 [ 0.19000651]]
=== expr ===
[[ 0.19824421 -0.30699027]
 [ 4.06285143  4.71971178]]


In [8]:
sess.close()