# 필수 파이썬 라이브러리

# Numpy

다차원 배열 객체

# pandas

구조화된 데이터(테이블)을 다양한 형식으로 가공할 수 있는 함수들을 제공

In [4]:
import numpy as np

In [5]:
data = [1,2,3,4]
arr = np.array(data)
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

In [7]:
type(np)

module

In [8]:
type(np.array)

builtin_function_or_method

In [9]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an
        object whose __array__ method returns an array, or any
        (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then
        the type will be determined as the minimum type required
        to hold the objects in the sequence.  This argument can only
        be used to 'upcast' the array.  For downcasting, use the
        .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy
        will only be made if __array__ returns a copy, if obj is a
        nested sequence, or if a copy is needed to satisfy any of the other
        requirements (`dtype`, `order`, etc.).

In [10]:
dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__r

In [11]:
data = (1,2,3,4)
arr2 = np.array(data)
arr2

array([1, 2, 3, 4])

In [12]:
arr.transpose()

array([1, 2, 3, 4])

In [13]:
data= [[1,2], [3,4]]
arr = np.array(data)
arr

array([[1, 2],
       [3, 4]])

In [14]:
arr.shape

(2, 2)

In [15]:
arr.ndim

2

In [21]:
from pandas import Series, DataFrame
import pandas as pd

# Series

In [30]:
obj = Series([4,7,-5, None])
obj

0    4.0
1    7.0
2   -5.0
3    NaN
dtype: float64

In [24]:
type(obj)

pandas.core.series.Series

In [31]:
obj.isnull()

0    False
1    False
2    False
3     True
dtype: bool

# DataFrame

In [35]:
data = {
    'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
    'year' : [2000, 2001, 2002, 2001, 2002],
}
frame = DataFrame(data)
frame

state  year
0    Ohio  2000
1    Ohio  2001
2    Ohio  2002
3  Nevada  2001
4  Nevada  2002

In [36]:
type(frame.state)

pandas.core.series.Series

In [37]:
frame.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object

In [38]:
frame.describe

<bound method NDFrame.describe of     state  year
0    Ohio  2000
1    Ohio  2001
2    Ohio  2002
3  Nevada  2001
4  Nevada  2002>

In [39]:
frame.ix[3]

state    Nevada
year       2001
Name: 3, dtype: object